version: '3.7'

services:
  usaon-vta-survey:
    image: "nsidc/usaon-vta-survey:${USAON_VTA_SURVEY_VERSION:-latest}"
    restart: "always"
    # HACK: run the app on the flask dev server with an adhoc cert.
    # TODO: Remove this `command` once we have a more mature solution for
    # distributing certs to our pre-production and production environment.
    command: "flask run --cert=adhoc --host 0.0.0.0"
    ports:
      - "443:5000"
    environment:
      # Flask Dance recommends setting this in production:
      #     https://flask-dance.readthedocs.io/en/v0.8.0/quickstarts/google.html#code
      - "OAUTHLIB_RELAX_TOKEN_SCOPE=1"
      - "USAON_VTA_PROXY"
